<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-09-13 22:16

import Vitrine.mixins
=======
# Generated by Django 5.1.6 on 2025-08-31 22:32

>>>>>>> 8750437900de8beadd7384be3adc93d797d65d08
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
<<<<<<< HEAD
        ('empresa', '0001_initial'),
=======
>>>>>>> 8750437900de8beadd7384be3adc93d797d65d08
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nome', models.CharField(help_text='Ex: Coleção Verão 2025, Mercearia, Roupas, Sobremesas...', max_length=60)),
                ('descricao', models.CharField(blank=True, help_text='Diga brevemente o que o catálogo aborda (se necessário)', max_length=80, null=True)),
                ('IMG', models.BinaryField(blank=True, editable=True, null=True, verbose_name='Imagem Binária')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogos', to='categoria.categoria')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogos', to='empresa.empresa')),
            ],
            options={
                'verbose_name_plural': 'Catálogos',
                'unique_together': {('empresa', 'nome')},
            },
            bases=(Vitrine.mixins.ImageHandlerMixin, models.Model),
=======
                ('título', models.CharField(help_text='Ex: Coleção Verão 2025, Mercearia, Roupas, Sobremesas...', max_length=60)),
                ('descrição', models.CharField(blank=True, help_text='Diga brevemente o que o catálogo aborda (se necessário)', max_length=80, null=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Uma imagem de capa para o catálogo', null=True, upload_to='thumbnails_catalogos/')),
                ('esta_ativo', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogos', to='categoria.categoria')),
            ],
            options={
                'verbose_name_plural': 'Catálogos',
            },
>>>>>>> 8750437900de8beadd7384be3adc93d797d65d08
        ),
    ]
