# Generated by Django 5.1.6 on 2025-08-31 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogos', to='empresa.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogo',
            unique_together={('empresa', 'título')},
        ),
    ]
