<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-09-13 22:16
=======
# Generated by Django 5.1.6 on 2025-08-31 22:32
>>>>>>> 8750437900de8beadd7384be3adc93d797d65d08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria (ex: Roupas, Vestidos)', max_length=100, unique=True)),
<<<<<<< HEAD
                ('cat_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='categoria.categoria', verbose_name='Categoria Principal')),
=======
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='categoria.categoria', verbose_name='Categoria Principal')),
>>>>>>> 8750437900de8beadd7384be3adc93d797d65d08
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
<<<<<<< HEAD
#
=======
>>>>>>> 8750437900de8beadd7384be3adc93d797d65d08
