# Generated by Django 5.1.6 on 2025-09-13 22:16

import Vitrine.mixins
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(help_text='Informe o CPF no formato 000.000.000-00', max_length=14, unique=True, verbose_name='CPF')),
                ('foto_perfil', models.BinaryField(blank=True, editable=True, null=True, verbose_name='Imagem Binária')),
                ('sobre', models.TextField(blank=True, help_text='Coloque aqui informações sobre você, slogan, um texto atrativo... como quiser!', null=True, verbose_name='Sobre')),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('detalhamento', models.CharField(blank=True, max_length=100, null=True)),
                ('Telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('X', models.URLField(blank=True, null=True, verbose_name='X (Twitter)')),
                ('Facebook', models.URLField(blank=True, null=True)),
                ('Instagram', models.URLField(blank=True, null=True)),
                ('Youtube', models.URLField(blank=True, null=True)),
                ('Github', models.URLField(blank=True, null=True)),
                ('LinkedIn', models.URLField(blank=True, null=True)),
                ('Kwai', models.URLField(blank=True, null=True)),
                ('Tiktok', models.URLField(blank=True, null=True)),
                ('Telegram', models.URLField(blank=True, null=True)),
                ('Whatsapp', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', Vitrine.mixins.ImageHandlerMixin),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
#