# Generated by Django 5.1.6 on 2025-09-13 22:16

import Vitrine.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('categoria', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, help_text='Use se o preço neste catálogo for diferente do padrão.', max_digits=10, null=True)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.catalogo')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('unidade', models.CharField(help_text='Unidade de venda do produto (ex: Peça, Kg, Caixa com 12, Pacote 500g)', max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do produto', max_digits=10)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('IMG', models.BinaryField(blank=True, editable=True, null=True, verbose_name='Imagem Binária')),
                ('catalogos', models.ManyToManyField(related_name='produtos', through='produto.Catalogo_Produto', to='catalogo.catalogo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='categoria.categoria')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='empresa.empresa')),
            ],
            bases=(Vitrine.mixins.ImageHandlerMixin, models.Model),
        ),
        migrations.AddField(
            model_name='catalogo_produto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogo_produto',
            unique_together={('catalogo', 'produto')},
        ),
    ]
